// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgkNLIXdKEzbP26lKZXJKch6Z36nf-gLo',
    appId: '1:910797221125:web:f5ad62e443a0a26ce9db6c',
    messagingSenderId: '910797221125',
    projectId: 'haedal-b2385',
    authDomain: 'haedal-b2385.firebaseapp.com',
    storageBucket: 'haedal-b2385.appspot.com',
    measurementId: 'G-6BK9ET27V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ri0oKMmIeJ2R-ay8HyiiHJSG9bJnQeM',
    appId: '1:910797221125:android:b8679b480d62b70be9db6c',
    messagingSenderId: '910797221125',
    projectId: 'haedal-b2385',
    storageBucket: 'haedal-b2385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsCqczT-x0hecykULk1cLelhUjuCmLfQ',
    appId: '1:910797221125:ios:4727553783a0bf4ee9db6c',
    messagingSenderId: '910797221125',
    projectId: 'haedal-b2385',
    storageBucket: 'haedal-b2385.appspot.com',
    iosClientId: '910797221125-fh9tq4oi0gijbqf0gsjjhl4qhr42nvdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.haedal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsCqczT-x0hecykULk1cLelhUjuCmLfQ',
    appId: '1:910797221125:ios:4727553783a0bf4ee9db6c',
    messagingSenderId: '910797221125',
    projectId: 'haedal-b2385',
    storageBucket: 'haedal-b2385.appspot.com',
    iosClientId: '910797221125-fh9tq4oi0gijbqf0gsjjhl4qhr42nvdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.haedal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgkNLIXdKEzbP26lKZXJKch6Z36nf-gLo',
    appId: '1:910797221125:web:f435457563ae576ee9db6c',
    messagingSenderId: '910797221125',
    projectId: 'haedal-b2385',
    authDomain: 'haedal-b2385.firebaseapp.com',
    storageBucket: 'haedal-b2385.appspot.com',
    measurementId: 'G-FD91EDNXT3',
  );
}
